AWSTemplateFormatVersion: 2010-09-09
Description: cfn-practice-rds
#-----------------------------------------------------------------------------------------
# RDS passsword
#-----------------------------------------------------------------------------------------
Parameters:
  DBPassword:
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: "make sure input correct password again"

Resources:
#-----------------------------------------------------------------------------------------
# RDS
#-----------------------------------------------------------------------------------------
  CfnRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      AvailabilityZone: !ImportValue AZ
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: cfn-rds
      DBName: CfnRDS
      DBSubnetGroupName: !Ref 'CfnRDSSubnetGroup'
      Engine: mysql
      EngineVersion: 5.7.37
      MasterUserPassword: !Ref 'DBPassword'
      MasterUsername: admin
      VPCSecurityGroups:
        - !Ref CfnRDSSecurityGroup

  CfnRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: temp
      DBSubnetGroupName: temp
      SubnetIds: 
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2

  CfnRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MySQL access for RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: cfn-security-group-RDS
      VpcId: !ImportValue VPCID

#-----------------------------------------------------------------------------------------
# Route53
#-----------------------------------------------------------------------------------------
  DNS: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: 'My hosted zone for example.com'
      Name: 'rds.endpoint'
      VPCs: 
        - 
          VPCId: !ImportValue VPCID
          VPCRegion: !Ref AWS::Region

  RDSDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: Creating records for mail server
      HostedZoneId: !Ref DNS
      RecordSets:
      - Name: db01.
        ResourceRecords: 
        - !GetAtt 'CfnRDSInstance.Endpoint.Address'
        TTL: '600'
        Type: CNAME
