version: 2.1
orbs:
  aws-cli:  circleci/aws-cli@2.0

jobs:
  create-cloudformation-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "create stack"
          command:  |
            set -e 
            aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | grep myteststack
            if [ $? nq 0 ];then
              aws cloudformation create-stack \
              --stack-name myteststack \
              --template-body file://service/infrastructure.yml \
              --parameters ParameterKey=DBPassword,ParameterValue=12345678
              aws cloudformation wait stack-create-complete \
              --stack-name myteststack
            fi

workflows:
  aws-cli:
    jobs:
      - create-cloudformation-stack
