version: 2.1
orbs:
  aws-cli:  circleci/aws-cli@2.0
  aws-cloudformation: orbss/aws-cloudformation@0.1.6
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  provisioning-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "template validate"
          command: |
            aws cloudformation validate-template --template-body file://cloudformation/vpc.yml;
            aws cloudformation validate-template --template-body file://cloudformation/ec2.yml;
            aws cloudformation validate-template --template-body file://cloudformation/rds.yml;
            aws cloudformation validate-template --template-body file://cloudformation/s3.yml;
      - aws-cloudformation/deploy:
          template-file-path: cloudformation/vpc.yml
          stack-name: mystack-vpc
          extra-arguments:  --no-fail-on-empty-changeset
      - aws-cloudformation/deploy:
          template-file-path: cloudformation/ec2.yml
          stack-name: mystack-ec2
          extra-arguments:  --no-fail-on-empty-changeset
      - aws-cloudformation/deploy:
          template-file-path: cloudformation/rds.yml
          stack-name: mystack-rds
          extra-arguments:  --no-fail-on-empty-changeset --parameter-overrides DBPassword=${DB_PASSWORD}
      - aws-cloudformation/deploy:
          template-file-path: cloudformation/s3.yml
          stack-name: mystack-s3
          extra-arguments:  --no-fail-on-empty-changeset
            
  execute-ansible-playbook:
    executor: ansible-playbook/default
    steps:
      - checkout
      - run:
          namme:  provide vault pass
          command: |
            echo "${VAULT_PASSWORD}" > ansible/vault_pass.txt;
      - ansible-playbook/install:
          version: 2.8.20
      - ansible-playbook/playbook:
          inventory:  ANSIBLE_INVENTORY
          playbook: ansible/playbook.yml
          private-key: ANSIBLE_SSH_KEY
          playbook-options: -u ec2-user --vault-password-file=ansible/vault_pass.txt

  execute-serverspec:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "2c:b2:97:c3:fd:d4:fc:50:ca:6a:5f:09:51:ac:73:65"
      - run: 
          name: install serverspec
          command:  |
            gem install serverspec;
            gem install yaml;
            gem install rake;
            gem install highline;
      - run:
          name: execute test
          command:  |
            cd serverspec;
            rake spec;

workflows:
  version:  2
  provisioning-deploy:
    jobs:
      - provisioning-stack
      - execute-ansible-playbook:
          requires:
            - provisioning-stack
      - execute-serverspec:
          requires:
            - execute-ansible-playbook
