version: 2.1
orbs:
  aws-cli:  circleci/aws-cli@2.0
jobs:
  test:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "create stack"
          command:  |
            aws cloudformation create-stack \
            --stack-name myteststack \
            --template-url https://circleci-cloudformation.s3.ap-northeast-1.amazonaws.com/rails-env.yml \
            --parameters ParameterKey=DBPassword,ParameterValue=12345678

workflows:
  aws-cli:
    jobs:
      - test
