version: 2.1
orbs:
  aws-cli:  circleci/aws-cli@2.0

jobs:
  create-cloudformation-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "create stack"
          command:  |
            set +e 
            aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | grep myteststack
            echo "aaaaaaaaaaa"
            echo $?
            echo "aaaaaaaaaaa"
            if [ $? -ne 0 ];  then
              echo 1111111111
              aws cloudformation create-stack \
              --stack-name myteststack2 \
              --template-body file://service/infrastructure.yml
              aws cloudformation wait stack-create-complete \
              --stack-name myteststack2
            elif [ $? -eq 0 ];  then
              echo 2222222222
              aws cloudformation update-stack \
              --stack-name myteststack2 \
              --template-body file://service/infrastructure.yml
              if [ $? -ne 0]; then
                echo 3333333333
                exit 0
              fi
              echo 4444444444
              aws cloudformation wait stack-update-complete \
              --stack-name myteststack2
            else
              echo 5555555555
            fi
            echo 6666666666

workflows:
  aws-cli:
    jobs:
      - create-cloudformation-stack
