version: 2.1
orbs:
  aws-cli:  circleci/aws-cli@2.0


jobs:
  create-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "create stack"
          command:  |
            set +e 
            aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE \| grep mystack
            if [ $? -ne 0 ];  then
              aws cloudformation create-stack \
              --stack-name mystack \
              --template-body file://service/infrastructure.yml
              aws cloudformation wait stack-create-complete \
              --stack-name mystack
            else
              aws cloudformation update-stack \
              --stack-name mystack \
              --template-body file://service/infrastructure.yml
              if [ $? -ne 0 ]; then
                exit 0
              fi
              aws cloudformation wait stack-update-complete \
              --stack-name mystack2
            fi






workflows:
  aws-cli:
    jobs:
      - create-stack
