version: 2.1
orbs:
  aws-cli:  circleci/aws-cli@2.0
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  create-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "create stack"
          command:  |
            set +e 
            aws cloudformation list-stacks --stack-status-filter UPDATE_COMPLETE | grep mystack
            if [ $? -eq 0 ];  then
              aws cloudformation update-stack \
              --stack-name mystack \
              --template-body file://service/infrastructure.yml
              if [ $? -ne 0 ]; then
                exit 0
              fi
              aws cloudformation wait stack-update-complete \
              --stack-name mystack
            else
              aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | grep mystack
              if [ $? -ne 0 ];  then
                aws cloudformation create-stack \
                --stack-name mystack \
                --template-body file://service/infrastructure.yml
                aws cloudformation wait stack-create-complete \
                --stack-name mystack
              fi
            fi
            
  execute-ansible-playbook:
    executor: ansible-playbook/default
    steps:
      - checkout
      - ansible-playbook/install:
          version: 2.29.6
      - ansible-playbook/playbook:
          inventory: ANSIBLE_INVENTORY
          playbook: ansible/playbook.yml
          playbook-options: -u ec2-user
          private-key: ANSIBLE_SSH_KEY

workflows:
  provisioning-deploy:
    jobs:
      - create-stack
      - execute-ansible-playbook:
          requires:
            - create-stack


