version: 2.1
orbs:
  aws-cli:  circleci/aws-cli@2.0
  aws-cloudformation: orbss/aws-cloudformation@0.1.6
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  provisioning-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "template validate"
          command: aws cloudformation validate-template --template-body file://service/infrastructure.yml
      - aws-cloudformation/deploy:
          template-file-path: service/infrastructure.yml
          stack-name: mystack
          extra-arguments:  --no-fail-on-empty-changeset
            
  execute-ansible-playbook:
    executor: ansible-playbook/default
    steps:
      - checkout
      - ansible-playbook/install:
          version: 2.8.20
      - ansible-playbook/playbook:
          inventory: ANSIBLE_INVENTORY
          playbook: ansible/playbook.yml
          playbook-options: -u ec2-user
          private-key: ANSIBLE_SSH_KEY

workflows:
  version:  2
  provisioning-deploy:
    jobs:
      - provisioning-stack
      - execute-ansible-playbook:
          requires:
            - provisioning-stack



