version: 2.1
orbs:
  aws-cli:  circleci/aws-cli@2.0
jobs:
  test:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "test output aws s3 ls"
          command:  "aws s3 ls"

workflows:
  aws-cli:
    jobs:
      - test
